platform :ios, '10.0'
use_frameworks!

target 'lazymails' do
	pod 'Whisper'
	pod 'Toaster'
	pod 'QRCodeReader.swift', '~> 8.0.3'
        pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
end
